version: "3"

services:
  conda:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 8087:8087
    volumes:
      - "/workspace/sho/:/work/"
    tty: true
    stdin_open: true
    deploy:
            resources:
                    reservations:
                            devices:
                                - driver: nvidia
                                  device_ids: ["3"]
                                  capabilities: [utility, compute, video, gpu]
